version: "3.8"

services:
  worker:
    container_name: notification-ms-worker-node
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
    networks:
      - notification-network
    restart: unless-stopped

networks:
  notification-network:
    external: true
